//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODEL
    {
        public int ID { get; set; }
        public int TYPE_ID { get; set; }
        public int COLOR_ID { get; set; }
        public byte CONVERTIBLE { get; set; }
    
        public virtual COLOR COLOR { get; set; }
        public virtual TYPE TYPE { get; set; }
    }
}
