//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODEL_DETAILS
    {
        public int MODEL_ID { get; set; }
        public int TYPE_ID { get; set; }
        public int COLOR_ID { get; set; }
        public byte MODEL_CONVERTIBLE { get; set; }
        public string COLOR_NAME { get; set; }
        public string TYPE_NAME { get; set; }
        public decimal TYPE_COST { get; set; }
    }
}
